# Generated by Django 5.1.5 on 2025-02-16 05:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('descripcion', models.TextField(max_length=60)),
                ('ingredientes', models.TextField(max_length=255)),
                ('pasos', models.TextField(max_length=255)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('tiempo_preparacion', models.IntegerField(blank=True, help_text='Indica el tiempo de preparación en minutos.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='recetas/')),
            ],
        ),
    ]
