# Generated by Django 5.1.5 on 2025-02-26 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_pais_alter_usuariopersonalizado_pais_provincia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='provincia',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.DeleteModel(
            name='Provincia',
        ),
        migrations.DeleteModel(
            name='UsuarioPersonalizado',
        ),
    ]
