# Generated by Django 5.1.5 on 2025-02-28 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infousuario',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='infousuario',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='infousuario',
            name='provincia',
        ),
        migrations.CreateModel(
            name='UbicacionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('infousuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion', to='usuarios.infousuario')),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicaciones', to='usuarios.pais')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicaciones', to='usuarios.provincia')),
            ],
        ),
    ]
