# Generated by Django 5.1.5 on 2025-03-01 04:26

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_infousuario_ciudad_remove_infousuario_pais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infousuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, default=usuarios.models.default_profile_image, null=True, upload_to=usuarios.models.user_directory_path),
        ),
    ]
